apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: py-tr-98-idif 
  janus-idp.io/tekton: py-tr-98-idif
  backstage.io/kubernetes-id: py-tr-98-idif
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: py-tr-98-idif
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  