apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: py-tr-98-idif
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: py-tr-98-idif 
  name: py-tr-98-idif
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: py-tr-98-idif
    weight: 100 
