apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: py-tr-98-idif
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: py-tr-98-idif 
  name: py-tr-98-idif
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: py-tr-98-idif 
